import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rating: {
    marginHorizontal: 16,
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  ratingHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  ratingHeaderImg: {
    width: 32,
    height: 32,
    marginRight: 23,
    marginLeft: 6,
    resizeMode: 'contain',
  },
  ratingHeaderTitle: {
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#2D1F21',
  },
  ratingExpanded: {
    borderTopColor: '#F2F2F2',
    borderTopWidth: 1,
    marginTop: 16,
    padding: 16,
    paddingBottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ratingPoint: {
    fontSize: 20,
    lineHeight: 32,
    paddingVertical: 18,
    paddingHorizontal: 12,
    borderRadius: 8,
    color: '#FFF',
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: '#DB147F',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,

    elevation: 24,
  },
  ratingFeedbackSmall: {
    color: '#5C595A',
    fontSize: 12,
  },
  ratingFeedback: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D1F21',
    lineHeight: 24,
    marginTop: 15,
  },
  ratingChart: {
    marginTop: 46,
    flexDirection: 'row',
  },
  ratingChartService: {
    position: 'relative',
    padding: 1,
    height: 10,
    borderRadius: 6,
    backgroundColor: '#DB147F',
    width: '42%',
    marginRight: -10,
    zIndex: 10,
  },
  ratingChartAverage: {
    position: 'relative',
    padding: 1,
    height: 10,
    borderRadius: 6,
    backgroundColor: '#32A4FC',
    width: '35%',
    marginRight: -10,
    zIndex: 5,
  },
  ratingChartOther: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#F2F2F2',
    width: '30%',
  },
  ratingChartCircle: {
    position: 'absolute',
    top: 1,
    right: 1,
    width: 8,
    height: 8,
    borderRadius: 100,
    backgroundColor: '#FFF',
  },
  ratingChartInfo1: {
    position: 'absolute',
    bottom: -20,
    left: 0,
    fontSize: 12,
    color: '#DB147F',
  },
  ratingChartInfo: {
    position: 'absolute',
    top: -20,
    right: -3,
    fontSize: 12,
    color: '#DB147F',
  },
  ratingChartInfo2: {
    position: 'absolute',
    bottom: -20,
    right: 0,
    fontSize: 12,
    color: '#857E7F',
  },
  ratingChartNote: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    marginTop: 30,
  },
  ratingChartNoteItem: {
    flexDirection: 'row',
    width: '50%',
    alignItems: 'center',
  },
  ratingChartNoteSquare1: {
    width: 14,
    height: 14,
    backgroundColor: '#32A4FC',
    borderRadius: 4,
    marginRight: 6,
  },
  ratingChartNoteSquare2: {
    width: 14,
    height: 14,
    backgroundColor: '#DB147F',
    borderRadius: 4,
    marginRight: 6,
  },
  ratingDesc: {
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 24,
    color: '#2D1F21',
    marginTop: 24,
  },
  ratingDescHighLine: {
    color: '#32A4FC',
  },
  ratingHeaderImgNqs: {
    width: 45,
    height: 35,
    borderRadius: 6,
    marginRight: 16,
    resizeMode: 'contain',
  },
  ratingImgNqs: {
    height: 57,
    width: 91,
  },
  ratingINqsList: {
    marginTop: 16,
  },
  ratingINqsItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: 12,
  },
  ratingINqsLabel: {
    width: '70%',
    fontSize: 14,
    color: '#2D1F21',
    marginBottom: 8,
  },
  ratingINqsValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FB8429',
  },
});

export default styles;
